In [41]:
%run 02_source_csd_per_vertex.py 0 0

USING: settings.json


  0%|                                                 | 0/32166 [00:02<?, ?it/s]


sub-001 | autoreject-sub-001-ses-01-001-motor-epo | finished processing in ~0 minutes.


In [38]:
csd_smooth

array([[-2.31827116e-19, -1.80674502e-19, -1.32664416e-19, ...,
        -4.27896588e-19, -4.62554412e-19, -5.03901651e-19],
       [ 1.76868970e-15,  1.42181138e-15,  1.09896870e-15, ...,
         2.37430422e-15,  2.53945905e-15,  2.73534581e-15],
       [ 3.43788227e-15,  2.76367065e-15,  2.13618343e-15, ...,
         4.61324149e-15,  4.93406643e-15,  5.31458502e-15],
       ...,
       [ 2.60652339e-16,  1.84030742e-16,  1.08421829e-16, ...,
         1.42221911e-15,  1.56101837e-15,  1.72780194e-15],
       [ 1.34326921e-16,  9.48349207e-17,  5.58640728e-17, ...,
         7.33206685e-16,  8.04765069e-16,  8.90750940e-16],
       [-1.66135490e-19, -1.27907876e-19, -9.18395937e-20, ...,
        -3.54042756e-19, -3.84014072e-19, -4.19838904e-19]])

In [20]:
mean_fif = np.mean(fif, axis=0)

In [29]:
np.dot(mean_fif.T, vertex_layers.T).T.shape

(11, 2401)

In [30]:
cortical_thickness

array([2.88891506, 2.11799097, 3.45607972, ..., 2.79436994, 2.84666514,
       2.44627571])

In [40]:
CSD_SMOOTH

[array([[-2.68816663e-19, -2.28938886e-19, -1.91598928e-19, ...,
         -1.72272823e-19, -2.44745829e-19, -3.29372774e-19],
        [ 1.03284167e-15,  9.45000146e-16,  8.64202875e-16, ...,
          3.09403390e-16,  3.50053479e-16,  3.94268532e-16],
        [ 2.00993406e-15,  1.83894894e-15,  1.68167485e-15, ...,
          6.02596656e-16,  6.81755525e-16,  7.67864868e-16],
        ...,
        [-5.36725262e-16, -4.93743333e-16, -4.54521028e-16, ...,
         -3.13471484e-16, -3.09913467e-16, -3.04323379e-16],
        [-2.76841425e-16, -2.54664508e-16, -2.34427022e-16, ...,
         -1.61698137e-16, -1.59888916e-16, -1.57036365e-16],
        [-1.54800611e-19, -1.28041069e-19, -1.02833375e-19, ...,
         -1.11890762e-19, -1.64547207e-19, -2.26546631e-19]]),
 array([[-2.31827116e-19, -1.80674502e-19, -1.32664416e-19, ...,
         -4.27896588e-19, -4.62554412e-19, -5.03901651e-19],
        [ 1.76868970e-15,  1.42181138e-15,  1.09896870e-15, ...,
          2.37430422e-15,  2.53945905e